---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/motorcycles":
    get:
      summary: list motorcycles
      responses:
        '200':
          description: successful
    post:
      summary: create motorcycle
      responses:
        '200':
          description: successful
  "/api/motorcycles/new":
    get:
      summary: new motorcycle
      responses:
        '200':
          description: successful
  "/api/motorcycles/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show motorcycle
      responses:
        '200':
          description: successful
    delete:
      summary: delete motorcycle
      responses:
        '200':
          description: successful
  "/api/rentals":
    get:
      summary: list rentals
      responses:
        '200':
          description: successful
    post:
      summary: create rental
      responses:
        '200':
          description: successful
  "/api/rentals/new":
    get:
      summary: new rental
      responses:
        '200':
          description: successful
  "/api/rentals/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show rental
      responses:
        '200':
          description: successful
    patch:
      summary: update rental
      responses:
        '200':
          description: successful
    put:
      summary: update rental
      responses:
        '200':
          description: successful
    delete:
      summary: delete rental
      responses:
        '200':
          description: successful
  "/api/user-data":
    get:
      summary: show user
      responses:
        '200':
          description: successful
  "/api/users":
    get:
      summary: list users
      responses:
        '200':
          description: successful
    post:
      summary: create user
      responses:
        '200':
          description: successful
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: 127.0.0.1:3000/
